(function() {
  document.writeln('<script type="text/javascript" src="libs/createjs/easeljs-0.6.0.min.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/createjs/preloadjs-0.3.0.min.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/createjs/soundjs-0.4.0.min.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/createjs/tweenjs-0.4.0.min.js"></script>');
	document.writeln('<script type="text/javascript" src="libs/createjs/movieclip-0.6.0.min.js"></script>');
	document.writeln('<script type="text/javascript" src="libs/createjs/ColorFilter.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/jquery/jquery.min.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/jquery/jquery.mousewheel.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/jquery/jquery.xml2json.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/jquery/jquery.imgpreload.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/jquery/jquery.cookie.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/pqp/Tristesse.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/pqp/Lng.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/pqp/Tag.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/pqp/Bag.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/pqp/Pqp.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/pqp/SimpleButton.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/greensock/plugins/CSSPlugin.min.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/greensock/easing/EasePack.min.js"></script>');
  document.writeln('<script type="text/javascript" src="libs/greensock/TweenMax.min.js"></script>');
}).call(this);